[[main]]
name = "About"
pageRef = "/about"
identifier = "4dn1PWNJpj"
weight = 2

[[main]]
name = "Posts"
weight = 3

[[main]]
name = "All"
parent = "Posts"
pageRef = "/posts"
weight = 4

[[main]]
name = "By tag"
parent = "Posts"
pageRef = "/tags"
weight = 5

[[main]]
identifier = "github"
pre = "github"
pageRef = "https://github.com/gibbyfree"
weight = 6

[[footer]]
name = "Tags"
pageRef = "/tags"
weight = 10

[[footer]]
name = "About"
pageRef = "/about"
weight = 20